### ISSUE TITLE
insert page: navbar

### ISSUE THREAD

**Issue by sagar005pawar** [ample-softech/Parking#2]
navabar error at the bottom of the navabar fix the margin(bottom) error fix it

**Comment by pujamitkari** [comment]
Exception caught during execution of merge command.
org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with
files:
Parking/WebContent/WEB-INF/jsp/basic/find.jsp
Exception caught during execution of merge command.
org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with
files:
Parking/WebContent/WEB-INF/jsp/basic/find.jsp


this exception i got while pull
