### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by sagar005pawar** [ample-softech/Parking#3]
needed one page that is space free for parking Registration

**Comment by pujamitkari** [comment]
Exception caught during execution of merge command. org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 
Parking/WebContent/WEB-INF/jsp/basic/find.jsp
Exception caught during execution of merge command. org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files: 
Parking/WebContent/WEB-INF/jsp/basic/find.jsp

**Comment by pujamitkari** [comment]
i got above exception while pull
